// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
with inserted_feed_follow as (
        INSERT INTO feed_follows (
            id, 
            created_at, 
            updated_at, 
            users_id,
            feeds_id
        )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, created_at, updated_at, users_id, feeds_id
)
select 
    inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.users_id, inserted_feed_follow.feeds_id, 
    feeds.name as feed_name,
    users.name as user_name
from inserted_feed_follow
inner join feeds on feeds.id = inserted_feed_follow.feeds_id
inner join users on users.id = inserted_feed_follow.users_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UsersID   uuid.UUID
	FeedsID   uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UsersID   uuid.UUID
	FeedsID   uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UsersID,
		arg.FeedsID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsersID,
		&i.FeedsID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}
