// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_posts_for_user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPostsForUser = `-- name: GetPostsForUser :many
with feed_list as (
        select 
            feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.users_id, feed_follows.feeds_id, 
            feeds.name as feed_name,
            users.name as user_name
        from feed_follows
        inner join feeds on feeds.id = feed_follows.feeds_id
        inner join users on users.id = feed_follows.users_id
        where feed_follows.users_id=$1
)

select 
        posts.id as post_id, 
        posts.published_at as pub_date, 
        posts.title as title, 
        posts.url as url,
        posts.description as description 
    from feed_list
    inner join posts on posts.feeds_id = feed_list.feeds_id
    order by posts.published_at DESC
    limit $2
`

type GetPostsForUserParams struct {
	UsersID uuid.UUID
	Limit   int32
}

type GetPostsForUserRow struct {
	PostID      uuid.UUID
	PubDate     time.Time
	Title       string
	Url         string
	Description string
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UsersID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.PostID,
			&i.PubDate,
			&i.Title,
			&i.Url,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
