// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_next_feed_to_fetch_single.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getNextFeedToFetchSingle = `-- name: GetNextFeedToFetchSingle :one
select id, name, url, last_fetched_at from feeds order by last_fetched_at asc nulls first
`

type GetNextFeedToFetchSingleRow struct {
	ID            uuid.UUID
	Name          string
	Url           string
	LastFetchedAt sql.NullTime
}

func (q *Queries) GetNextFeedToFetchSingle(ctx context.Context) (GetNextFeedToFetchSingleRow, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetchSingle)
	var i GetNextFeedToFetchSingleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}
