// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedbyurl.sql

package database

import (
	"context"
)

const getFeedByURL = `-- name: GetFeedByURL :one
select id, created_at, updated_at, url, name, users_id, last_fetched_at from feeds where url = $1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Name,
		&i.UsersID,
		&i.LastFetchedAt,
	)
	return i, err
}
