// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedlist.sql

package database

import (
	"context"
)

const getFeedList = `-- name: GetFeedList :many
select id, created_at, updated_at, url, name, users_id, last_fetched_at from feeds
`

func (q *Queries) GetFeedList(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.Name,
			&i.UsersID,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
